---
title: "Reference Scenario"
author: "RSG, Inc"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
    fig_caption: true
    theme: spacelab
params:
  fig.path: fig-single_scenario/
  ref_db: "Q:/Projects/OR/Oregon DOT/SWIM_WOC7/Data/fromClient/Database/Ref26_NoFB.db"
  scenario_name: Reference
  facet: COUNTY
  county_control_file: "../../../inputs/t0/county_controls.csv"
  mpo_control_file: "../../../inputs/t0/mpo_controls.csv"
  diff_year: 2040
  index_year: 2020
  use_leaflet: true
editor_options: 
  chunk_output_type: console
---

```{r setup, echo = FALSE, message=FALSE, warning = FALSE}
library(knitr)
opts_chunk$set(echo = TRUE, fig.keep = TRUE, fig.path = params$fig.path)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(methods)
library(tidyverse)
library(DT)
library(RSQLite)
library(swimr)
```


```{r setdb}
# This is the path to the scenario SWIM databases; direct these to your
# local paths.
ref_db <- params$ref_db
db <- dbConnect(SQLite(), dbname=ref_db)

# scenario_name <- "Reference"
scenario_name <- params$scenario_name

# Update to reflect scope of analysis.
# If you wish to focus on the Metro and Bend MPOs, for instance, change `facet`
# to "MPO" and facet_levels to `c("Metro", "Bend")`
# facet <- "COUNTY"
facet <- params$facet
facet_levels <-  c("Multnomah", "Washington", "Clackamas")

# The tables will only show data from these years.
years <- c(2010, 2020, 2025, 2040, 2050)
# years <- c(2019, 2020, 2025, 2031, 2040, 2043, 2045, 2050)

# The list MPOs to plot - note that in this version "Longview/Kelos/Rainier" and "Walla Walla Valley" are dropped
MPOs <- c("Albany","Bend", "Corvallis", "Eugene/Springfield","Medford", "METRO", "METRO_CLARK","Middle Rogue", "NonMPO", "Halo", "Salem/Keizer", "BRM", "CALM", "SOABM")

# The leaflet plots show a comparison between the scenarios in a specific year.
# Set this to the year you wish to study.
# diff_year <- 2040
diff_year <- params$diff_year
index_year <- params$index_year

# show leaflet plots; FALSE will skip them (saving disk space and time)
# use_leaflet <- FALSE
use_leaflet <- params$use_leaflet

# Read the control files
# County
county_controls <- read.csv(params$county_control_file)
colnames(county_controls)[1] <- "county"
# MPO
mpo_controls <- read.csv(params$mpo_control_file)
colnames(mpo_controls)[1] <- "MPOmodeledzones"
```



# Scenario Description


```{r scenario, results='asis'}
# update to reflect current scenario
scen_info <- tibble(
  Name = basename(ref_db),
  Scenario = scenario_name,
  `File date` = file.info(ref_db)$mtime
)

kable(scen_info, caption = "Scenario Information")
```

# Socioeconomics {.tabset}

## Map

```{r leaflet, fig.cap="Change in socioeconomic data over model run."}
if(use_leaflet){
  change_leaflet(db, year1 = 2010, year2 = diff_year)
} else {
  print("Leaflet plots skipped with `use_leaflet` option")
}
```

## Population


```{r se}
se <- extract_se(db, "MPOmodeledzones", controls = mpo_controls) %>%
  filter(year %in% years)
```

```{r tab_pop, results='asis'}
pop <- se %>% filter(var == "population") %>%
  yearly_summary(group = c("color_var"), var = "y")

kable(pop, caption = "Population by MPO", digits = 2)
```

```{r tab_pop_forecast, results='asis'}
pop <- se %>% filter(var == "population") %>%
  yearly_summary(group = c("color_var"), var = "y", use_forecast = TRUE)

kable(pop[,sort_fields(colnames(pop))], caption = "Population by MPO", digits = 2)
```


```{r plot_se1, fig.cap="Population and employment in selected areas."}
plot_sevar(db, color_var = facet, color_levels = facet_levels, controls = FALSE, index = TRUE, index_year=index_year)
```

```{r plot_se1_index, fig.cap="Indexed Population and employment in selected areas."}
plot_sevar(db, color_var = facet, color_levels = facet_levels, index = TRUE, controls = county_controls, index_year=index_year)
```


```{r plot_pop_mpo_forecast, fig.cap="Population with Forecast- all MPOs.", fig.width=8, fig.height=12}
plot_sevar(db, color_var = "MPOmodeledzones", controls=mpo_controls, var="population", index_year=index_year)
```


```{r plot_pop_mpo_forecast_index, fig.cap="Indexed population with forecast - all MPOs.", fig.width=8, fig.height=12}
plot_sevar(db, color_var = "MPOmodeledzones", controls=mpo_controls, index = TRUE, var="population", index_year=index_year)
```

## Employment
```{r tab_emp, results='asis'}
emp <- se %>% filter(var == "employment") %>%
  yearly_summary(group = "color_var", var = "y")

kable(emp, caption = "Employment by MPO", digits = 2)
```

```{r tab_emp_forecast, results='asis'}
emp <- se %>% filter(var == "employment") %>%
  yearly_summary(group = "color_var", var = "y", use_forecast = TRUE)

kable(emp[,sort_fields(colnames(emp))], caption = "Employment by MPO", digits = 2)
```


```{r plot_se2, fig.cap="Population and employment in selected areas."}
plot_sevar(db, color_var = facet, color_levels = facet_levels, controls = FALSE, index = TRUE, index_year=index_year)
```

```{r plot_se2_index, fig.cap="Indexed Population and employment in selected areas."}
plot_sevar(db, color_var = facet, color_levels = facet_levels, index = TRUE, controls = county_controls, index_year=index_year)
```


```{r plot_emp_mpo_forecast, fig.cap="Employment with Forecast- all MPOs.", fig.width=8, fig.height=12}
plot_sevar(db, color_var = "MPOmodeledzones",controls=mpo_controls, var="employment", index_year=index_year)
```


```{r plot_emp_mpo_forecast_index, fig.cap="Indexed employment with forecast - all MPOs.", fig.width=8, fig.height=12}
plot_sevar(db, color_var = "MPOmodeledzones", controls=mpo_controls, index = TRUE, var="employment", index_year=index_year)
```

## Historical Trends
```{r plot_history, fig.cap="Historical population trends in selected areas."}
plot_history(db, counties = facet_levels)
```


# Transportation {.tabset}

## Link Validation
```{r plot_validation, fig.cap="Link Validation"}
plot_countcomparison(db, 2010)
```

```{r plot_truckvalidation, fig.cap="Truck Validation"}
plot_countcomparison(db, 2013, TRUE)
```

```{r plot_facility_validation, fig.cap = "Link Validation by Facility Type"}
plot_countcomparison(db, 2010) + facet_wrap(~ FacType, scales = "free")
```

```{r plot_historical_atr, fig.cap="AAWDT count and projection at selected ATR locations"}
plot_traffic_count(db, atr =
                     c("03-011", "10-006", "03-013", "34-009", "24-022",
                       "15-020", "03-018", "10-008"))
```


## VMT

```{r tab_vmt}
vmt <- extract_vmt(db, "MPO", index = FALSE) %>%
  filter(year %in% years) %>%
  group_by(year, MPO) %>%
  summarise(vmt = sum(vmt)) %>%
  yearly_summary("MPO", "vmt")

kable(vmt, caption = "VMT by MPO", digits = 2)
```


```{r plot_vmt, fig.cap="VMT by facility type."}
plot_vmt(db, facet, facet_levels, index = FALSE, index_year=index_year)
```

```{r plot_vmt_index, fig.cap="Indexed VMT by facility type."}
plot_vmt(db, facet, facet_levels, index_year=index_year)
```

```{r plot_vmt_mpo, fig.cap="VMT by facility type - all MPO's."}
plot_vmt(db, "MPO", index_year=index_year)
```



## Mode Split
```{r tab_trips, results='asis'}
trips <- extract_trips(db, "MPO") %>%
  filter(year %in% years) %>%
  group_by(year, facet_var) %>%
  summarise(trips = sum(trips)) %>%
  yearly_summary("facet_var", "trips")

kable(trips, caption = "Total Trips by MPO", digits = 2)
```

```{r tab_trips_mpo, results='asis'}
tab_mode <- extract_trips(db, "MPO", facet_levels = c("METRO", "METRO_CLARK")) %>%
  filter(year %in% years) %>%
  filter(facet_var == "METRO") %>%
  group_by(year, mode) %>%
  summarise(trips = sum(trips)) %>%
  yearly_summary("mode", "trips")

kable(tab_mode, caption = "Metro MPO Trips by Mode", digits = 2)
```

```{r mode_share, fig.cap="Share of trips produced by mode"}
plot_trips(db, facet, facet_levels, share = TRUE, index_year=index_year)
```

```{r mode_share_mpo, fig.cap="Share of trips produced by mode - all MPOs"}
plot_trips(db,  share = TRUE, index_year=index_year)
```

```{r mode_vol, fig.cap="Total trips produced by mode."}
plot_trips(db, facet, facet_levels, share = FALSE, index = FALSE)
```

```{r mode_vol_mpo, fig.cap="Total trips produced by mode - all MPOs"}
plot_trips(db, share = FALSE, index_year=index_year)
```



## TLFD

```{r plot_tlfd, fig.cap = "Trip length frequency distribution."}
plot_tlfd(db, facet, facet_levels, index_year=index_year)
```

```{r plot_tlfd_cum, fig.cap = "Cumulative trip length frequency distribution."}
plot_tlfd(db, facet, facet_levels, cumulative = TRUE, index_year=index_year)
```

```{r plot_tlfd_mpo, fig.cap = "Trip length frequency distribution - all MPO's."}
plot_tlfd(db, "MPO", MPOs, index_year=index_year)
```

## Log Sums
```{r plot_logsum, fig.cap = "Destination choice model logsums."}
plot_logsums(db, facet, facet_levels, index_year=index_year)
```

```{r plot_logsum_mpo, fig.cap = "Destination choice model logsums - all MPO's"}
plot_logsums(db, "MPO", c("Bend", "Corvallis", "EugeneSpringfield",
               "Metro", "NonMPO", "RogueValley", "SalemKeizer"), index_year=index_year)
```


# Economics{.tabset}

```{r aa_diagnostics}
troubleshoot_aa(db)
```


## Built Floorspace
```{r plot_floorspace, fig.cap="Floorspace by type."}
plot_floorspace(db, facet, facet_levels, index_year=index_year)
```

```{r plot_floorspace_mpo, fig.cap="Floorspace by type - all MPO's."}
plot_floorspace(db, index_year=index_year)
```

## Rent and Occupancy Rate
```{r plot_rent, fig.cap = "Unit rent by floorspace type."}
plot_floorspace(db, facet, facet_levels, price = TRUE, index_year=index_year)
```

```{r plot_rent_mpo, fig.cap = "Unit rent by floorspace type - all MPO's"}
plot_floorspace(db, price = TRUE, index_year=index_year)
```

```{r plot_occupancy, fig.cap = "Occupancy rate by floorspace type."}
plot_occupancy(db, facet, facet_levels, index_year=index_year)
```

```{r plot_occupancy_mpo, fig.cap = "Occupancy rate by floorspace type - all MPO's"}
plot_occupancy(db, index_year=index_year)
```


## Employment

```{r plot_employment, fig.cap="Labor output by sector."}
plot_employment(db, facet, facet_levels, index_year=index_year)
```

```{r plot_employment_mpo, fig.cap="Labor output by sector - all MPO's."}
plot_employment(db, index_year=index_year)
```

## Labor Output

```{r plot_gdp, fig.cap="Comparison of labor output by sector."}
plot_gdp(db, facet, facet_levels, index_year=index_year)
```

```{r plot_gdp_mpo, fig.cap="Comparison of labor output by sector - all MPO's."}
plot_gdp(db, index_year=index_year)
```

## Labor Force Participation

Specifically, the ratio of workers to individuals 15 or older.

```{r plot_wapr, fig.cap = "Workforce participation."}
plot_wapr(db, facet, facet_levels, index_year=index_year)
```

```{r plot_wapr_mpo, fig.cap = "Workforce participation."}
plot_wapr(db, "MPO", index_year=index_year)
```
