####################################################################
# PopulationSim Properties
####################################################################

# Multiprocess parameters
multiprocess: True
num_processes: @POPSIMSPG2.NUM.PROCESSES@
slice_geography: PUMA

# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 15
MAX_BALANCE_ITERATIONS_SIMULTANEOUS: @POPSIMSPG2.MAX.ITERATIONS@


# Geographic Settings
# ------------------------------------------------------------------
geographies: [REGION, PUMA, AZONE]
seed_geography: PUMA


# Tracing
# ------------------------------------------------------------------
#trace_geography:
#  MAZ: 1
#  TAZ: 310


# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : seed_households.csv
    index_col: hh_id
  - tablename: persons
    filename : seed_persons.csv
    column_map:
      SPORDER: per_num
    # drop mixed type fields that appear to have been incorrectly generated
  - tablename: geo_cross_walk
    filename : geo_cross_walk.csv
  - tablename: AZONE_control_data
    filename : control_alpha.csv
  - tablename: REGION_control_data
    filename : control_region.csv

# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: WGTP
household_id_col: hh_id
total_hh_control: num_hh


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - summary_AZONE
    - summary_AZONE_PUMA
    - expanded_household_ids
    - summary_hh_weights


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: household_id
  households:
    filename: spg2_synthetic_households.csv
    columns:
      - NP
      - BLD
      - NWESR
      - VEH
      - hh_id
      - HHINC2009
      - AZONE
  persons:
    filename: spg2_synthetic_persons.csv
    columns:
      - per_num
      - AGEP
      - SEX
      - hh_id
      - ESR
      - SCH
      - INDP
      - OCCP
      - occupation
      - occupationLabel
      - split_industry_id
      - split_industry


# Steps for base mode
# ------------------------------------------------------------------
models:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    - sub_balancing.geography=AZONE
    - expand_households
    - summarize
    - write_tables
    - write_synthetic_population
    
    
multiprocess_steps:
  - name: mp_seed_balancing
    begin: input_pre_processor
  - name: mp_sub_balancing_AZONE
    begin: sub_balancing.geography=AZONE
    num_processes: @POPSIMSPG2.NUM.PROCESSES@
    slice:
      tables:
        - slice_crosswalk
        - crosswalk
      # don't slice any tables not explicitly listed above in slice.tables
      except: True
      # the following tables are added by sub_balancer and should be coalesced
      coalesce:
        - AZONE_weights
        - AZONE_weights_sparse
        - trace_AZONE_weights
  - name: mp_summarize
    begin: expand_households

resume_after:
