####################################################################
# PopulationSim Properties
####################################################################


# Algorithm/Software Configuration
# ------------------------------------------------------------------
INTEGERIZE_WITH_BACKSTOPPED_CONTROLS: True
SUB_BALANCE_WITH_FLOAT_SEED_WEIGHTS: False
GROUP_BY_INCIDENCE_SIGNATURE: True
USE_SIMUL_INTEGERIZER: True
USE_CVXPY: False
max_expansion_factor: 15


# Geographic Settings
# ------------------------------------------------------------------
geographies: [REGION, SEED, SUBSEED]
seed_geography: SEED


# Tracing
# ------------------------------------------------------------------
#trace_geography:
#  MAZ: 1
#  TAZ: 310


# Input Data Tables
# ------------------------------------------------------------------
# input_pre_processor input_table_list
input_table_list:
  - tablename: households
    filename : seed_households.csv
    index_col: hh_id
  - tablename: persons
    filename : seed_persons.csv
    column_map:
      SPORDER: per_num
    # drop mixed type fields that appear to have been incorrectly generated
  - tablename: geo_cross_walk
    filename : geo_cross_walk.csv
  - tablename: SUBSEED_control_data
    filename : control_subseed.csv
  - tablename: REGION_control_data
    filename : control_region.csv

# Reserved Column Names
# ------------------------------------------------------------------
household_weight_col: WGTP
household_id_col: hh_id
total_hh_control: num_hh


# Control Specification File Name
# ------------------------------------------------------------------
control_file_name: controls.csv


# Output Tables
# ------------------------------------------------------------------
# output_tables can specify either a list of output tables to include or to skip
# if neither is specified, then no tables will be written

output_tables:
  action: include
  tables:
    - summary_SUBSEED
    - summary_SUBSEED_SEED
    - expanded_household_ids
    - summary_hh_weights


# Synthetic Population Output Specification
# ------------------------------------------------------------------
#

output_synthetic_population:
  household_id: household_id
  households:
    filename: spg1_synthetic_households.csv
    columns:
      - NP
      - NWESR
      - VEH
      - hh_id
      - HINCP
      - ADJINC
      - hhsize_cat
      - hhinc_cat
  persons:
    filename: spg1_synthetic_persons.csv
    columns:
      - per_num
      - AGEP
      - SEX
      - hh_id
      - ESR
      - INDP
      - OCCP
      - occupation
      - occupationLabel
      - split_industry_id
      - split_industry


# Steps for base mode
# ------------------------------------------------------------------
run_list:
  steps:
    - input_pre_processor
    - setup_data_structures
    - initial_seed_balancing
    - meta_control_factoring
    - final_seed_balancing
    - integerize_final_seed_weights
    - sub_balancing.geography=SUBSEED
    - expand_households
    - summarize
    - write_tables
    - write_synthetic_population

  #resume_after: expand_households
